### ISSUE TITLE
unfinished string near '<eof>'

### ISSUE THREAD

**Issue by Cheatoid** [thegrb93/StarfallEx#1200]
Steps to reproduce:
1. Download [samples.zip](https://github.com/thegrb93/StarfallEx/files/7073502/samples.zip).
2. Extract `sample_GLua.lua` to `<GarrysMod>/garrysmod/lua` folder.
3. Extract `sample_Starfall.lua` to `<GarrysMod>/garrysmod/data/starfall` folder.
4. Start Garry's Mod (in singleplayer), open developer console and enter the following command:
    `lua_openscript sample_GLua.lua`
    - Observe, the script has run successful and printed: "Hello from Cheatoid"
5. Get Starfall - Processor tool. Open `sample_Starfall.lua` file and try to spawn it.
    - Observe, there is a script error: `SF:sample_Starfall.lua:1: unfinished string near '<eof>'`

I expected the script to run just fine. This was working fine at some point (a couple months ago).
Fix it.

**Comment by x4fx77x4f** [comment]
I encountered this problem myself at one point doing the exact same thing you're doing, but with the intention of storing binary data before `--@includedata` existed.
The sample runs fine if it is run indirectly, like so:
```lua
--@server
--@include sample_starfall.lua
dofile('sample_starfall.lua')
```
The problem is in the editor. The editor replaces 0x09 bytes (tabs) with 4 0x20 bytes (4 spaces) each, and replaces 0x0d bytes (carriage returns) with 0x0a bytes (line feeds). This can be demonstrated by using this code:
```lua
#!/usr/bin/env luajit
local handle = io.open('bytefuck.txt', 'wb+')
handle:write("--@server\n")
local function out(i)
	handle:write(string.format("-- 0x%02x: %c\n", i, i))
end
for i=0x00, 0x1f do
	out(i)
end
for i=0x7f, 0xff do
	out(i)
end
handle:write("\n")
handle:close()
```
...opening `bytefuck.txt` in the editor, saving it to a new file, using `diff` to identify the changed lines, and then finding those lines in a hex editor to see what the byte was changed to.
This should be fixed by not changing the actual loaded bytes in the editor, even if it causes the file to not render correctly.

**Comment by Cheatoid** [comment]
> The editor replaces 0x09 bytes (tabs) with 4 0x20 bytes (4 spaces) each, and replaces 0x0d bytes (carriage returns) with 0x0a bytes (line feeds).

Updated: [sample_Starfall_v2.zip](https://github.com/thegrb93/StarfallEx/files/7073815/sample_Starfall_v2.zip)

I updated the sample, so all tabs are now escaped as `\t` within the binary string literal.
There are no line feeds (LF) or carriage returns (CR) at all, because these are already escaped, it is all on a single line, simple said.

The problem remains, also since the file has extension of `.lua`, an addon can not re-save it to disk, suggesting that SF is doing some fuckery during file upload perhaps.
Also you can spawn the SF without opening the editor by using the explorer tree in the spawn menu in case you didn't know, **and** still the problem remains.

> The problem is in the editor.

So, I doubt it is the editor at fault, actually.

**Comment by x4fx77x4f** [comment]
> I updated the sample, so all tabs are now escaped as \t within the binary string literal.
There are no line feeds (LF) or carriage returns (CR) at all, because these are already escaped, it is all on a single line, simple said.

I tested your new sample and found that it runs fine without creating any errors.

> The problem remains,

I just tested both the old and new sample on the latest commit (d0cd55a) and haven't observed any change. The same bytes still get mangled, and the same behavior occurs. (Oh, and since I forgot to say it earlier: The first sample fails, but with a different error which was caused by `loadstring` not properly handling the `nil` value returned by `bit.decompress` since decompression failed.)

> also since the file has extension of `.lua`, an addon can not re-save it to disk, suggesting that SF is doing some fuckery during file upload perhaps.

StarfallEx doesn't update the file, but it does change the version loaded in the editor, which is used when uploading.

> Also you can spawn the SF without opening the editor by using the explorer tree in the spawn menu in case you didn't know, and still the problem remains.

How? If I just click on it, nothing happens (placing down a chip afterwards will just spawn whatever happens to be in the editor at that time). Double clicking just opens it in the editor. There's also no option for it in the context menu.

**Comment by Cheatoid** [comment]
> I tested your new sample and found that it runs fine without creating any errors.

That's probably because you running the file "indirectly"? If so, that's beyond the scope of this issue.

> Oh, and since I forgot to say it earlier: The first sample fails, but with a different error which was caused by loadstring not properly handling the nil value returned by bit.decompress since decompression failed.

This obviously hints that you have re-saved the first sample somehow, most likely with SF editor as you probably changed the extension.
In which case, for the first sample the tabs within string literal would be replaced with 4 spaces as you mentioned earlier, thus decompression would fail for this reason, passing a nil value to loadstring bla bla bla.
Anyways that's a wrong error. I am having an error stated in title of this issue, on both samples. I do have latest Starfall pulled down (which happens to be d0cd55a).

By the way, see the edit on my previous comment.
With that being said... Are there any other places where "editor" does such a terrible thing?

**Comment by x4fx77x4f** [comment]
> That's probably because you running the file "indirectly"? If so, that's beyond the scope of this issue.

I'm not running the samples indirectly.

> This obviously hints that you have re-saved the first sample somehow, most likely with SF editor as you probably changed the extension.

I did not resave the samples, or change the extension.

I closed all tabs containing the samples, ensured the files in the directory were correct, opened the file in the editor, and then spawned a chip without saving.

https://user-images.githubusercontent.com/70858634/131283829-7f5f9044-60d7-4df8-ad67-c4f624e5deb4.mp4

**Comment by Cheatoid** [comment]
Here's what I got on a clean GMod install with only StarfallEx addon installed (running on Windows 10, with GMod on x86_64 branch):
### v1 sample
![v1](https://user-images.githubusercontent.com/13347909/131287180-4aa075ee-2516-4aa4-bdd7-fd0c82c306ea.png)

### v2 sample
![v2](https://user-images.githubusercontent.com/13347909/131287181-c07030da-7e24-45ea-a31b-008443cda7f2.png)

**Comment by Cheatoid** [comment]
I don't understand how come validation be successful on your side, I don't even have to spawn it to see the error, it is actually right there on the status bar of the editor.
Also, check your side, you have lowercase `S` on those files when it should be `sample_Starfall`/`sample_Starfall_v2` with uppercase `S`. Garry's `file` library explicitly does this when writing to a file, it lowercases the filename.
Proving you have in fact resaved the file somehow, again 😕

Platform specific, for real?

**Comment by thegrb93** [comment]
Binary data wont work in the editor

**Comment by Cheatoid** [comment]
> Binary data wont work in the editor

Well, it is not about the editor. I don't care about that.
The script should run fine on its own, but in fact it doesn't. That's the issue.

**Comment by x4fx77x4f** [comment]
> Also, check your side, you have lowercase `S` on those files when it should be `sample_Starfall`/`sample_Starfall_v2` with uppercase `S`. Garry's `file` library explicitly does this when writing to a file, it lowercases the filename.

I tested both lowercase and not. I renamed the files manually, because I am aware that uppercase letters in paths can cause problems in Garry's Mod.

> Proving you have in fact resaved the file somehow, again 😕

You're testing my patience. The SHA-256 sum matches the ones in your two screenshots.

> Platform specific, for real?

I just tested on the x86_64 branch, on gm_flatgrass, with the only addon being a fresh copy of StarfallEx, on both Windows (via Proton) and Linux (natively), and found that the behavior *does* vary based on platform.

![Screenshot on Windows](https://user-images.githubusercontent.com/70858634/131289119-3d01bda2-da37-4980-9ef9-ddc0fda3de75.png)

![Screenshot on Linux](https://user-images.githubusercontent.com/70858634/131289121-ae74945f-1b0e-4866-8b61-5bd44b0d20aa.png)

**Comment by Cheatoid** [comment]
> On Windows, neither sample compiles. They both fail with "unfinished string near '<eof>'".

There, you're experiencing the same issue as me. Alright, it is a Windows-only issue. How exciting.

> Somewhere along the way, the loaded data is being truncated.

Apparently yes. But the question is where? 👀

**Comment by x4fx77x4f** [comment]
![Screenshot on Windows](https://user-images.githubusercontent.com/70858634/131291468-f84ea5dd-b1b7-44ff-907d-04ba0de0b50d.png)
🎉
By the way, we might want to report this issue [upstream](https://github.com/Facepunch/garrysmod-issues). `file.Open`'s behavior should be consistent across platforms, or there should at least be a notice on the wiki page for it.

**Comment by Cheatoid** [comment]
@x4fx77x4f I have tested your `binary_fix` branch on my side. Yes, that's it, the file wasn't open in binary mode.
That's what you get for doing things manually.

> By the way, we might want to report this issue upstream.

There's nothing to report towards GMod; [`file.Read`/`file.Write`](https://github.com/Facepunch/garrysmod/blob/master/garrysmod/lua/includes/extensions/file.lua) has always been fine, using `rb`/`wb` (at least since 2013 or so).
It is Starfall to blame here, because it does things like `file.Read` manually, for no particular reason.
