### ISSUE TITLE
NextBot issues

### ISSUE THREAD

**Issue by ANormalTwig** [thegrb93/StarfallEx#1359]
Writing a NextBot to a net message with `net.writeEntity` doesn't seem to work. Also `nextbot.create`'s second argument isn't optional

**Comment by thegrb93** [comment]
Will need to see what metatable nextbots are in multiplayer client. This code can find that probably.

```lua
for k, v in pairs(debug.GetRegistry()) do
    if v == debug.getmetatable(nextbot) then
        print(k)
    end
end
```

**Comment by ReasonableScripts** [comment]
i just did a trace on client to the nextbot and got the metatable name and its "Entity" but on server its "NextBot"

**Comment by thegrb93** [comment]
Both of those are registered in starfall so it should be working fine as of yesterday's update

**Comment by thegrb93** [comment]
I think the issue is you're sending that bot entities in a table, then reading the table in client before the bot entities are valid in client.

**Comment by thegrb93** [comment]
Tried it in a dedicated server and didn't have an issue.

**Comment by ANormalTwig** [comment]
`nextbot.create`'s second argument still isn't optional, and I still get nil from net.readEntity
```lua
-- @name Generic
-- @author A Nomral Twig
-- @shared

-- Shared
-- @name Generic
-- @author A Nomral Twig
-- @shared

-- Shared
if SERVER then
    -- Server
    hook.add("ClientInitialized", "Test", function(ply)
        local nb = nextbot.create(chip():getPos(), "models/Kleiner.mdl")
        net.start("Ent")
        net.writeEntity(nb)
        net.send()
        print("NextBot sent.")
    end)
    return
end
-- Client
net.receive("Ent", function()
    net.readEntity(function(e)
        print(e)
    end)
end)
```
![image](https://user-images.githubusercontent.com/78218557/179332751-ba35e5cf-5409-412e-8c48-49c00386afdf.png)

**Comment by ANormalTwig** [comment]
Does this for me on singleplayer, local multiplayer, and on a dedicated server.

**Comment by thegrb93** [comment]
I tested with that exact example and it worked in all 3

**Comment by adamnejm** [comment]
Ran the code on singleplayer, local multiplayer and p2p. Works as intended. Possible addon conflict?
